spring:
  profiles:
    default: dev

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    url: jdbc:mysql://118.67.128.252:3306/findtogether?serverTimezone=Asia/Seoul
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.MySQL57Dialect
    defer-datasource-initialization: true


logging.level:
  org.hibernate.SQL: debug
  org.springframework.boot.autoconfigure: error
  #org.hibernate.type: trace
